[build-system]
requires = ["scikit-build-core", "numpy", "scipy"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.packages = ["python/pyalps"]
cmake.verbose = true
#build-dir = "./build_alps"
#build.tool-args = ["-j8", "-l13"]
logging.level = "DEBUG"

[tool.scikit-build.cmake.define]
Boost_SRC_DIR = {env="Boost_SRC_DIR"}
CMAKE_CXX_FLAGS = "-fPIC -fpermissive -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_TIMER_ENABLE_DEPRECATED -DBOOST_BIND_GLOBAL_PLACEHOLDERS"
CMAKE_C_FLAGS = "-fPIC"
ALPS_PYTHON_WHEEL = "ON"
ALPS_BUILD_FORTRAN = "ON"

[[tool.scikit-build.overrides]]
if.platform-system = "^darwin"
cmake.define.CMAKE_CXX_FLAGS = "-fPIC -stdlib=libc++ -fpermissive -DBOOST_NO_AUTO_PTR -DBOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF -DBOOST_TIMER_ENABLE_DEPRECATED -DBOOST_BIND_GLOBAL_PLACEHOLDERS"
cmake.define.Boost_SRC_DIR = {env="Boost_SRC_DIR"}
cmake.define.ALPS_BUILD_FORTRAN = "ON"
cmake.define.CMAKE_C_FLAGS = "-fPIC"
cmake.define.ALPS_PYTHON_WHEEL = "ON"

[project]
name = "pyalps"
version = "2.3.3"
authors = [
  { name="Sergei Iskakov", email="siskakov@umich.edu" },
]
license = {text = "MIT License"}

dependencies = ["numpy", "scipy"]

description = "Python Applications and Libraries for Physics Simulations"
readme = "README-py.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: C++',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: Implementation :: CPython',
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]

[project.urls]
Homepage = "https://alps.comp-phys.com"
Issues = "https://github.com/ALPSim/ALPS/issues"


[project.optional-dependencies]
tests = [
  'coverage>=5.0.3',
  'pytest',
  'pytest-benchmark[histogram]>=3.2.1',
]

[tool.cibuildwheel]
skip = ["*-musllinux*"]
test-requires = "pytest"
test-command = "pytest {project}/test"
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
before-all = "dnf install -y epel-release; dnf config-manager --set-enabled powertools; dnf install -y fftw-devel hdf5-devel openblas-devel wget; pipx install patchelf==0.14.5.0 --force"
#before-build=""
test-command = "pytest {project}/test/pyalps"

[tool.cibuildwheel.macos]
before-all = "brew reinstall hdf5 fftw gfortran"
test-command = "pytest {project}/test/pyalps"
