#  Copyright Matthias Troyer and Synge Todo 2009-2013.
#   Permission is hereby granted, free of charge, to any person obtaining
#   a copy of this software and associated documentation files (the “Software”),
#   to deal in the Software without restriction, including without limitation
#   the rights to use, copy, modify, merge, publish, distribute, sublicense,
#   and/or sell copies of the Software, and to permit persons to whom the
#   Software is furnished to do so, subject to the following conditions:
#  
#   The above copyright notice and this permission notice shall be included
#   in all copies or substantial portions of the Software.
#  
#   THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS
#   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#   DEALINGS IN THE SOFTWARE.


#
# basic C++ tools
# 

#
# quickbook
# 

# If Boost precompiled libraries found, don't build quickbook,
# since sources are not available.
if (NOT Boost_FOUND AND ALPS_BUILD_DOC)
  set (QUICKBOOK_SOURCES "")
  foreach (D "${Boost_ROOT_DIR}/tools/quickbook/detail" "${Boost_ROOT_DIR}/tools/quickbook/src")
    set (FILES actions.cpp actions_class.cpp block_element_grammar.cpp
               block_grammar.cpp code_snippet.cpp collector.cpp 
               dependency_tracker.cpp
               doc_info_actions.cpp doc_info_grammar.cpp document_state.cpp files.cpp
               glob.cpp grammar.cpp id_generation.cpp id_manager.cpp id_xml.cpp input_path.cpp 
               include_paths.cpp main_grammar.cpp 
               markups.cpp native_text.cpp phrase_element_grammar.cpp phrase_grammar.cpp 
               post_process.cpp quickbook.cpp state.cpp string_ref.cpp 
               syntax_highlight.cpp template_stack.cpp utils.cpp values.cpp)
    foreach(S ${FILES})
      if(EXISTS ${D}/${S})
        set(QUICKBOOK_SOURCES ${QUICKBOOK_SOURCES} ${D}/${S})
      endif(EXISTS ${D}/${S})
    endforeach(S)
  endforeach (D)
  add_executable(quickbook ${QUICKBOOK_SOURCES})
  target_link_libraries(quickbook ${ALPS_BOOST_LIBRARY_NAME})
  if (NOT ALPS_BUILD_SOURCE)
    install(TARGETS quickbook RUNTIME DESTINATION bin COMPONENT tools)
  endif (NOT ALPS_BUILD_SOURCE)
endif (NOT Boost_FOUND AND ALPS_BUILD_DOC)

if (NOT ALPS_BUILD_SOURCE)

  add_subdirectory(alea)

  #
  # Script to setup ALPS_HOME, PATH, LD_LIBRARY_PATH, PYTHONPATH
  #

  configure_file(alpsvars.sh.in ${CMAKE_CURRENT_BINARY_DIR}/alpsvars.sh @ONLY)
  configure_file(alpsvars.csh.in ${CMAKE_CURRENT_BINARY_DIR}/alpsvars.csh @ONLY)
  install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/alpsvars.sh ${CMAKE_CURRENT_BINARY_DIR}/alpsvars.csh DESTINATION bin COMPONENT tools)

  set (TOOLS parameter2xml parameter2hdf5 convert2xml compactrun lattice2xml pevaluate pconfig
             poutput printgraph txt2archive xml2archive snap2vtk)
  foreach(program ${TOOLS})
    add_executable(${program} ${program}.C)
    target_link_libraries(${program} alps)
    install(TARGETS ${program} RUNTIME DESTINATION bin COMPONENT tools) 
  endforeach(program)

  #
  # ngs tools
  # 
  foreach(program p2h5)
    add_executable(${program} ${program}.cpp)
    target_link_libraries(${program} alps)
    install(TARGETS ${program} RUNTIME DESTINATION bin COMPONENT tools) 
  endforeach(program)


if(SQLite_FOUND)
  include_directories(${SQLite_INCLUDE_DIR})
  add_executable(archive archive.cpp archive_index.cpp archive_node.cpp archive_plot.cpp
    archive_sqlite.cpp archive_xml.cpp)
  target_link_libraries(archive alps ${SQLite_LIBRARIES})
  install(TARGETS archive RUNTIME DESTINATION bin  COMPONENT tools)
endif(SQLite_FOUND)

#
# legacy shell scripts that stay around for backwards compatibility until the new solutions are there
#

  install(PROGRAMS archivecat convert2html convert2text extractgp extracthtml 
          extractmpl  extracttext extractxmgr plot2gp plot2html plot2mpl 
          plot2text plot2xmgr use_local_stylesheet xslttransform 
          DESTINATION bin COMPONENT tools)

#
# lattice-preview and helper program
#

  configure_file(config.py.in ${CMAKE_CURRENT_BINARY_DIR}/config.py)
  configure_file(lattice-preview.in ${CMAKE_CURRENT_BINARY_DIR}/lattice-preview)
  install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/lattice-preview DESTINATION bin COMPONENT tools)
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/config.py preview.py license.py
    DESTINATION lib/python/alps COMPONENT tools)

  #
  # Analytical continuation with MaxEnt
  #

  if(LAPACK_FOUND)
    add_definitions(${LAPACK_DEFINITIONS} -DBIND_FORTRAN_LOWERCASE_UNDERSCORE)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${LAPACK_LINKER_FLAGS}")
    add_executable(maxent maxent.cpp maxent_helper.cpp maxent_simulation.cpp maxent_parms.cpp)
    target_link_libraries(maxent alps ${LAPACK_LIBRARY} ${BLAS_LIBRARY})
    install(TARGETS maxent RUNTIME DESTINATION bin COMPONENT tools)
   endif(LAPACK_FOUND)

  #
  # alpspython and vispython scripts
  # 
  
  set(ALPSPYTHON_CONFIGURED FALSE)
  if(PYTHON_INTERPRETER AND NOT ALPS_PACKAGE_LIBRARIES)
      set(PYTHONPATH "${ALPS_PYTHON_LIB_DEST_ROOT}")
      set(PYTHONBIN "${PYTHON_INTERPRETER}")
      string(CONFIGURE [[
        set(PROJECT_SOURCE_DIR "@PROJECT_SOURCE_DIR@")
        set(PYTHONBIN "@PYTHONBIN@")
        set(PYTHONPATH "${CMAKE_INSTALL_PREFIX}/@PYTHONPATH@")
        message(STATUS ": ${PYTHONPATH}")
        message(STATUS ": ${PYTHONBIN}")
        configure_file(${PROJECT_SOURCE_DIR}/tool/alpspython.in ${CMAKE_INSTALL_PREFIX}/bin/alpspython )
        ]] install_script @ONLY)
      install(CODE ${install_script})
    set(ALPSPYTHON_CONFIGURED TRUE)
  endif(PYTHON_INTERPRETER AND NOT ALPS_PACKAGE_LIBRARIES)

endif (NOT ALPS_BUILD_SOURCE)
